baseURL = "https://shalfallen.github.io/"
languageCode = 'en-us'
title = 'Shaltear.'
theme="cactus"
copyright = "Hendridev"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[params]
  mainSectionTitle = "Blog"
  [params.comments]
    enabled = true
    # engine = "disqus" # in progress
